apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    namespace: hello-world-prod
    name: in-cluster
  project: default
  sources:
    # Chart from Chart Repo
    - chart: hello-world
      repoURL: https://helm.github.io/examples
      targetRevision: 0.1.0
      helm:
        valueFiles:
        - $values/multiple-source-application/values-prod.yaml
    # Values from Git
    - repoURL: 'https://github.com/rockchico/argo-cd-helm-values-demo.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
