apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-umbrella-chart
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: helm-umbrella-chart/apps
    repoURL: https://github.com/rockchico/argo-cd-helm-values-demo.git
    targetRevision: HEAD
    directory: {}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true